openapi: 3.0.0
info:
  title: LLM Chat API
  description: API for LLM chat with Supabase and LiteLLM
  version: 1.0.0
servers:
  - url: https://{project-ref}.supabase.co/functions/v1
    variables:
      project-ref:
        default: your-project-ref
paths:
  /chat-handler:
    post:
      summary: Handle a chat message
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message]
              properties:
                message: { type: string, example: "Hello" }
                chat_id: { type: string, format: uuid, example: "123e4567-e89b-12d3-a456-426614174000" }
                model: { type: string, example: "gpt-4" }
                stream: { type: boolean, default: false }
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  chat_id: { type: string, format: uuid }
                  response: { type: string }
            text/plain:
              schema: { type: string }
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '404': { description: Chat not found }
        '500': { description: Server error }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT